### ISSUE TITLE
update roadmap

### ISSUE THREAD

**Issue by alexeyzvegintcev** [9ci/angle-grinder#415]
- [x] convert coffee -> js

- [x] make unit tests pathing

- [x] update to angular 1.5

- [x] update to angular 1.6

- [x] update to angular 1.7

- [ ] cleanup/upgrade package.json see https://github.com/9ci/angle-grinder/issues/416

- [x] test and fix based on results of running examples apps, make sure example apps are running properly in master

- [x] setup webpack config to be able to use modules and modify source to use imports and exports. create index.js in key tool directories

- [x] update code to angularjs-annotate and classes where appropriate and refactor to patter where export is doing module name or service name etc...

- [x] convert example docs app to be built with an entry point and webpack so it comes up with npm start 

- [ ] publish as a package to npm @yakworks/ag and make it work more like lodash where packages are moved up to root and we can import like @yakworks/ag/gridz etc...

- [ ] deprecate grails-plugin and move any groovy source out to rally, gorm-tools or rcm

- [ ] as intermediate step try to config webpack and/or grunt to push bundles into grails plugin like we do now, this will go away though.

## RCM

- [ ] check for RCM for running app using plugin and bundles

- [ ] fix problems where we are importing things twices like jquery and bootstrap

- [ ] convert coffee -> js in RCM

- [ ] once app is working we can start on breaking out js to be in a node project that will depend on the @yakworks/ag package from npm
